### ISSUE TITLE
[Bug]: Debugify Conflict/Incompatibility 

### ISSUE THREAD

**Issue by greensad** [Fuzss/horseexpert#3] opened 2022-12-27 18:13 UTC
### Mod Loader (Required)

Quilt

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.0

### Notes (Required)

No information appears while holding or equipping the monocle and looking at or interacting with a horse, tried with minimum installation, tried with tamed and untamed horses.

**Comment by Fuzss** [comment] 2022-12-27 22:50
Cannot reproduce.

You need to equip the monocle in the Trinkets head slot and look at the horse (do not sit on it). The horse must be tamed. With those conditions met everything works as intended on Quilt.

**Comment by greensad** [comment] 2022-12-29 06:20
> Cannot reproduce.
> 
> You need to equip the monocle in the Trinkets head slot and look at the horse (do not sit on it). The horse must be tamed. With those conditions met everything works as intended on Quilt.

When I have a little more time I'll try to figure out what's going on, I must have had some mods I considered to be minimal, maybe a quilted fabric api or something. Can guarantee the conditions you listed were met, multiple restarts of the game. But I'll do some poking and include a log.

**Comment by Fuzss** [comment] 2022-12-29 08:31
It's not quilted fabric api, I tested with that.

**Comment by greensad** [comment] 2023-01-24 01:01
Hey @Fuzss I know it's been a month but I had some time to test this today, I found the incompatibility; **[Debugify](https://modrinth.com/mod/debugify)**. This makes sense as **[ToolTipFix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix)** is included in Debugify and might interfere with your horse tooltips. Because of that I'm not sure if this is fixable on your end so I'll submit a ticket on Debugify's repository as well. 

Log: https://mclo.gs/WDhKNmL

**Comment by Fuzss** [comment] 2023-05-06 05:15
That's better fixed on my end, already made sure this works on the 1.19.3 port, should probably backport the fix at some point.

**Comment by Fuzss** [comment] 2023-11-06 18:22
Closing this now as it's resolved in the 1.19.3+ versions. Backport will come at some point, but is not a priority.

**Closed by Fuzss** 2023-11-06 18:22 UTC
Labels: bug
